#!/usr/bin/env bash

set -eu

outdir="$(readlink -f output/mt_contig/pbjelly)"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# source PBJelly... why? no idea.
# shellcheck disable=SC1091
source bin/pbsuite/setup.sh
pbjelly="$(readlink -f bin/pbsuite/bin/Jelly.py)"

# files
contigs="$(readlink -f output/mt_contig/pilon/Scaffold2.fasta)"
my_contigs="${outdir}/contigs.fasta"
long_reads="data/asw12_20170627_merged.fq.gz"
pbjelly_lr="${outdir}/long_reads.fastq"

# PBJelly config
# SOME PROBLEM PASSING THE OUTPUT DIR TO SETUP
jelly_protocol="${outdir}/jelly_protocol.xml"
cat <<- _EOF_ > "${jelly_protocol}"
<jellyProtocol>
    <reference>${my_contigs}</reference>
    <outputDir>${outdir}</outputDir>
    <blasr>-minMatch 8 -minPctIdentity 70 -bestn 1 -nCandidates 20
    -maxScore -500 -nproc 50 -noSplitSubreads</blasr>
    <input baseDir="$(dirname "${pbjelly_lr}")">
        <job>$(basename "${pbjelly_lr}")</job>
    </input>
</jellyProtocol>
_EOF_

# copy contigs
printf "[ %s: Copying contigs to outdir ]\n" "$(date)"
cp "${contigs}" "${my_contigs}"

# convert reads
printf "[ %s: Unzipping long reads ]\n" "$(date)"
bin/bbmap/reformat.sh "in=${long_reads}" "out=${pbjelly_lr}"

# run pbjelly in a subshell
(
cd "${outdir}" || exit 1
printf "[ %s: Opening a subshell and changing wd ]\n" "$(date)"
printf "pwd: %s\n" "$(pwd)"

# setup pbjelly
printf "[ %s: Running PBJelly setup ]\n" "$(date)"
"${pbjelly}" setup "${jelly_protocol}"

# pbjelly steps
printf "[ %s: Running PBJelly mapping ]\n" "$(date)"
"${pbjelly}" mapping "${jelly_protocol}"

printf "[ %s: Running PBJelly support ]\n" "$(date)"
"${pbjelly}" support "${jelly_protocol}"

printf "[ %s: Running PBJelly extraction ]\n" "$(date)"
"${pbjelly}" extraction "${jelly_protocol}"

printf "[ %s: Running PBJelly assembly ]\n" "$(date)"
"${pbjelly}" assembly "${jelly_protocol}"

printf "[ %s: Running PBJelly output ]\n" "$(date)"
"${pbjelly}" output "${jelly_protocol}"
    )