#!/usr/bin/env bash

set -eu

samtools=bin/samtools/samtools

outdir="output/mt_contig/long_reads_mapped_to_sr_assembly"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# files
 mapped_long_reads="output/mt_contig/"
mapped_long_reads+="long_reads_mapped_to_sr_assembly/lr_mapped.bam"
tmp_fq="${outdir}/mt_long_reads_tmp.fq"
output_lr="${outdir}/mt_long_reads.fq.gz"
cmd_log="${outdir}/filterbyname.log"

# expand BAM to fq 
printf "[ %s: Converting BAM to fq for names ]\n" "$(date)"
cmd=( bin/bbmap/reformat.sh
          "in=${mapped_long_reads}"
          "out=${tmp_fq}" )

shopt -s extglob
printf "Running command:\n"
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" 2> "${cmd_log}"

# filter reads
printf "[ %s: Running filterbyname.sh temporary fq ]\n" "$(date)"
cmd=( bin/bbmap/filterbyname.sh 
          "in=data/asw12_20170627_merged.fq.gz"
          "names=${tmp_fq}"
          "include=t"
          "substring=name"
          "zl=9"
          "out=${output_lr}")

shopt -s extglob
printf "Running command:\n"
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" 2>> "${cmd_log}"

# remove tmp files
rm "${tmp_fq}"

exit 0
