#!/usr/bin/env bash

set -eu

outdir="output/mt_contig/long_reads_mapped_to_sr_assembly"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

samtools=bin/samtools/samtools

pilon_fasta="output/mt_contig/pilon/Scaffold2.fasta"
mt_assembly="${outdir}/mt_assembly.fasta"
long_reads="data/asw12_20170627_merged.fq.gz"
my_lr="${outdir}/lr.fq.gz"
output_bam="${outdir}/lr_mapped.bam"

# filter reads < 4 kb
printf "[ %s: Filtering long reads ]\n" "$(date)"
cmd=( bin/bbmap/reformat.sh 
          "in=${long_reads}" 
          "out=${my_lr}"
          minlength=4000 )
cmd_log="${outdir}/reformat.log"

shopt -s extglob
printf "Running command:\n"
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" &> "${cmd_log}"

# index contigs
printf "[ %s: Running bwa index ]\n" "$(date)"
sed "s/^>.*/>Scaffold2/" "${pilon_fasta}" \
    > "${mt_assembly}"
bwa index "${mt_assembly}"

# map long reads
printf "[ %s: Running bwa mem ]\n" "$(date)"
# npscarf settings: 
# -k11 -W20 -r10 -A1 -B1 -O1 -E1 -L0 -a -Y
cmd1=( bwa mem -t 50
          -x ont2d
          ${mt_assembly}
          ${my_lr} )
cmd1_log="${outdir}/bwa_mem.log"

cmd2=( "${samtools}" view -h -F 2308 )
cmd2_log="${outdir}/samtools_view.log"

cmd3=( "${samtools}" sort -@ 50 -l 9 -m 5G
           -o "${output_bam}"
           --reference "${mt_assembly}" )
cmd3_log="${outdir}/samtools_sort.log"

shopt -s extglob
printf "Piping commands:\n"
printf "%s " "${cmd1[@]//+([[:blank:]])/ }"
printf " | "
printf "%s " "${cmd2[@]//+([[:blank:]])/ }"
printf " | "
printf "%s " "${cmd3[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd1[@]}" 2> "${cmd1_log}" \
    | "${cmd2[@]}" 2> "${cmd2_log}" \
    | "${cmd3[@]}" 2> "${cmd3_log}"

printf "[ %s: Running samtools index ]\n" "$(date)"
"${samtools}" index "${output_bam}"

exit 0

## canu assemble these reads?
