#!/usr/bin/env bash

set -eu

outdir="test"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

nanopore_assembly="test/tig00000001.fa"
pe_reads="data/pe_merged.fastq.gz"
bwa_log="${outdir}/bwamem.log"
samtools_log="${outdir}/samtools.log"
output_bam="test/pe_mapped.bam"

printf "[ %s: Running bwa index ]\n" "$(date)"
bwa index "${nanopore_assembly}"

printf "[ %s: Running bwa mem and piping to samtools sort ]\n" "$(date)"
bwa mem \
    -t 20 \
    -p \
    "${nanopore_assembly}" \
    "${pe_reads}" \
    2> "${bwa_log}" \
    | samtools sort \
        -@ 20 \
        -m 200G \
        -l 9 \
        -o "${output_bam}" \
        2> "${samtools_log}"

printf "[ %s: Running samtools index ]\n" "$(date)"
samtools index "${output_bam}"

exit 0
