#!/usr/bin/env bash

set -eu

MAPPING="test/pe_mapped.bam"

outdir="test/stats"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# mapped SAM statistics (and mapped raw reads)
samtools view -F 2308 ${MAPPING} \
    | bin/bbmap/reformat.sh \
    in=stdin.sam \
    out=stdout.fastq \
    mappedonly=t \
    primaryonly=t \
    pairedonly=t \
    "bhist=${outdir}/bhist_mapped.txt" \
    "qhist=${outdir}/qhist_mapped.txt" \
    "qchist=${outdir}/qchist_mapped.txt" \
    "aqhist=${outdir}/aqhist_mapped.txt" \
    "bqhist=${outdir}/bqhist_mapped.txt" \
    "lhist=${outdir}/lhist_mapped.txt" \
    "gchist=${outdir}/gchist_mapped.txt" \
    gcbins=auto \
    "ehist=${outdir}/ehist_mapped.txt" \
    "qahist=${outdir}/qahist_mapped.txt" \
    "indelhist=${outdir}/indelhist_mapped.txt" \
    "mhist=${outdir}/mhist_mapped.txt" \
    "idhist=${outdir}/idhist_mapped.txt" \
    idbins=auto \
    | bin/bbmap/repair.sh \
    in=stdin.fastq \
    repair=t \
    "out=${outdir}/mapped_reads.fastq.gz" \
    zl=9

# output coverage on filtered alignments
# samtools view -h -F 2308 "${MAPPING}" \
#     | bin/bbmap/pileup.sh \
#     in=stdin.sam \
#     secondary=f \
#     "hist=${outdir}/hist.txt" \
#     "basecov=${outdir}/basecov.txt" \
#     "bincov=${outdir}/bincov.txt" 
