#!/usr/bin/env bash

set -eu

printf "[ %s: Normalise kmer coverage with bbnorm ]\n" \
    "$(date)"

# make outdir
outdir="test/bbnorm"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# files
input_fq="test/stats/mapped_reads.fastq.gz"
output_fq="${outdir}/normalised_reads.fastq.gz"
log_file="${outdir}/bbnorm.log"

cmd=( bin/bbtools/bbnorm.sh
        "in=${input_fq}"
        "out=${output_fq}"
        ziplevel=9
        target=60 min=30 prefilter ecc
        "khist=${outdir}/hist_before.txt"
        "khistout=${outdir}/hist_after.txt"
        "peaks=${outdir}/peaks.txt" )

# run bbnorm
printf "[ %s: Running bbnorm ]\n" "$(date)"
shopt -s extglob
printf "Final command line:\n"
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" 2> "${log_file}"

printf "[ %s: Done ]\n" "$(date)"
exit 0
