#!/usr/bin/env bash

set -eu

outdir="output/mt_contig/pilon"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

max_memory="500G"
my_pilon=( java -Xmx${max_memory} -jar bin/pilon/pilon-1.22.jar )

genome="output/mt_contig/mt_reads_mapped_to_sr_assembly/mt_assembly.fasta"
frags="output/mt_contig/mt_reads_mapped_to_sr_assembly/mt_mapped.bam"

pilon_log="${outdir}/pilon.log"

printf "[ %s: Running pilon ]\n" "$(date)"
"${my_pilon[@]}" \
    --genome "test/tig00000001.fa" \
    --frags "test/pe_mapped.bam" \
    --output "Scaffold2" \
    --outdir "${outdir}" \
    --tracks \
    &> "${pilon_log}"
