#!/usr/bin/env bash

set -eu

outdir="output/mt_contig/unicycler"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

 mapped_long_reads="output/mt_contig/"
mapped_long_reads+="long_reads_mapped_to_sr_assembly/mt_long_reads.fq.gz"
trimmed_reads="${outdir}/trimmed_mt_reads.fastq.gz"

# run porechop
cmd=( porechop
          --threads 50
          -i "${mapped_long_reads}"
          -o "${trimmed_reads}" )
cmd_log="${outdir}/porechop.log"

shopt -s extglob
printf "Running command:\n"
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" &> "${cmd_log}"

exit 0
