#!/usr/bin/env bash

mira_bin="$(readlink -f bin/mira/mira)"
read_file="$(readlink -f test/stats/mapped_reads.fastq.gz)"

outdir="test/mira"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# generate config file
cat <<- _EOF_ > test/mira/mira.config
# project settings
project = asw_nanopore_mtdna
job = genome,denovo,accurate
parameters = -GENERAL:number_of_threads=50 \
    -NW:mrnl=0:cac=warn:cnfs=no \
    SOLEXA_SETTINGS "--noclipping -CL:pec=no" \
    -CO:msr=no 

# readgroup settings
readgroup = pe
data = ${read_file}
technology = solexa
autopairing
segment_placement = ---> <---
strain_name = asw_mtdna
_EOF_

# run mira
(
    cd "${outdir}" || exit 1
    "${mira_bin}" mira.config
    )

exit 0
