#!/usr/bin/env bash

set -eu

# function for printing command line and running command
run_cmd () {
    local -n _cmd
    _cmd=$1
    local _log_file="${2}"

    shopt -s extglob
    printf "Running command:\n"
    printf "%s " "${_cmd[@]//+([[:blank:]])/ }"
    printf "\n"
    shopt -u extglob

    "${_cmd[@]}" &> "${_log_file}"
}

outdir="output/mt_contig/opera"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# files
contigs="output/mt_contig/pilon/Scaffold2.fasta"
my_contigs="${outdir}/contigs.fasta"
long_reads="data/asw12_20170627_merged.fq.gz"
samtools_dir="bin/samtools"
opera_dir="bin/opera-lg"
short_reads="output/mt_contig/mapping/mapped_reads.fastq.gz"
sr1="${outdir}/r1.fasta"
sr2="${outdir}/r2.fasta"

# OPERA-long reads steps
# 1. make bwa index
cp "${contigs}" "${my_contigs}"
cmd=( bwa index "${my_contigs}" )
run_cmd cmd "${outdir}/bwa_index.log"

exit 1

# run opera ... this needs to be done manually because the OPERA script is
# broken
printf "[ %s: Running OPERA-LG ]\n" "$(date)"
opera_log="${outdir}/opera.log"
cmd=( bin/opera-lg/OPERA-long-read.pl
          --contig-file "${contigs}"
          --kmer 41 
          --long-read-file "${long_reads}"
          --output-prefix "asw_mtdna"
          --output-directory "${outdir}"
          --num-of-processors 50
          --opera "${opera_dir}"
          --illumina-read1 "${sr1}"
          --illumina-read2 "${sr2}" )

