#!/usr/bin/env bash

set -eu

outdir="$(readlink -f output/mt_contig/pbjelly)"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# source PBJelly... why? no idea.
# shellcheck disable=SC1091
source bin/pbsuite/setup.sh
pbjelly="bin/pbsuite/bin/Jelly.py"

# files
contigs="$(readlink -f output/mt_contig/pilon/Scaffold2.fasta)"
long_reads="data/asw12_20170627_merged.fq.gz"
pbjelly_lr="${outdir}/long_reads.fastq"

# PBJelly config
jelly_protocol="${outdir}/jelly_protocol.xml"
cat <<- _EOF_ > "${jelly_protocol}"
<jellyProtocol>
    <reference>${contigs}</reference>
    <outputDir>${outdir}</outputDir>
    <blasr>-minMatch 8 -minPctIdentity 70 -bestn 1 -nCandidates 20
    -maxScore -500 -nproc 50 -noSplitSubreads</blasr>
    <input baseDir="$(dirname "${pbjelly_lr}")">
        <job>$(basename "${pbjelly_lr}")</job>
    </input>
</jellyProtocol>
_EOF_

# convert reads
bin/bbmap/reformat.sh "in=${long_reads}" "out=${pbjelly_lr}"

# setup pbjelly
"${pbjelly}" setup "${jelly_protocol}"

exit 1

# pbjelly steps
"${pbjelly}" mapping "${jelly_protocol}"
"${pbjelly}" support "${jelly_protocol}"
"${pbjelly}" extraction "${jelly_protocol}"
"${pbjelly}" assembly "${jelly_protocol}"
"${pbjelly}" output "${jelly_protocol}"
