#!/usr/bin/env bash

set -eu

outdir="output/mt_contig/opera"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# files
contigs="$(readlink -f output/mt_contig/pilon/Scaffold2.fasta)"
long_reads="$(readlink -f data/asw12_20170627_merged.fq.gz)"
samtools_dir="$(readlink -f bin/samtools)"
opera_dir="$(readlink -f bin/opera-lg)"
short_reads="$(readlink -f output/mt_contig/mapping/mapped_reads.fastq.gz)"
sr1="$(readlink -f ${outdir}/r1.fasta)"
sr2="$(readlink -f ${outdir}/r2.fasta)"

# deinterleave R1 and R2
printf "[ %s: Demuxing reads ]\n" "$(date)"
bbmap_log="${outdir}/bbmap.log"
bin/bbmap/reformat.sh \
    "in=${short_reads}" \
    "out=${sr1}" \
    "out2=${sr2}" \
    2> "${bbmap_log}"

# run opera
printf "[ %s: Running OPERA-LG ]\n" "$(date)"
opera_log="${outdir}/opera.log"
# --samtools-dir "${samtools_dir}"
cmd=( bin/opera-lg/OPERA-long-read.pl
          --contig-file "${contigs}"
          --kmer 41 
          --long-read-file "${long_reads}"
          --output-prefix "asw_mtdna"
          --output-directory "${outdir}"
          --num-of-processors 50
          --opera "${opera_dir}"
          --illumina-read1 "${sr1}"
          --illumina-read2 "${sr2}" )

shopt -s extglob
printf "Final command line:\n"
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" &> "${opera_log}"
